server:
  port: 8081

spring:
  datasource:
    name:
    url: jdbc:mysql://host.docker.internal:3306/febs_nacos?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=UTC
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
